spring:
  thymeleaf:
    prefix: "file:src/main/resources/templates/"
    suffix: ".html"
    cache: false
    check-template-location: true
    mode: HTML

  web:
    resources:
      static-locations: "file:src/main/resources/static/"
      chain:
        cache: false
      cache:
        period: 0

  devtools:
    livereload:
      enabled: true
    restart:
      poll-interval: 1000
      quiet-period: 400


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
